apiVersion: v1  # Change to v1beta1 or later
kind: Service
metadata:
  name: prt-web-website-service
spec:
  type: NodePort
  selector:
    app: prt-web-website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30010
