-- CREATE DATABASE ASSIGN3

-- USE ASSIGN3





-- CREATE TABLE CUSTOMER (CUSTOMER_ID INT , FIRST_NAME VARCHAR(30) , LAST_NAME VARCHAR(20),
-- EMAIL VARCHAR(30), ADDRESS VARCHAR(30), CITY VARCHAR(20)  , STATE VARCHAR(20) , ZIP INT)



-- INSERT INTO CUSTOMER VALUES(10,'NEHA','SIGH','NEHA@GMAIL.COM','SHANTINAGAR','BANGALORE','KARNATAKA',11),
-- 							(20,'SUNIL','KUMAR','SUNIL@GMAIL.COM','GANDHI NAGAR','BANGALORE','KARNATAKA',12),
-- 							(30,'GAGANA','CHOWDHARY','GAGANA@GMAIL.COM','K R PURAM','SAN JOSE','KERALA',13),
-- 							(40,'CHANDAN','GOWDA','CHANDAN@GMAIL.COM','VV NAGAR','SHIVA KASHI','TAMIL NADU',14),
-- 							(50,'NASEEHA','SIGH','NASEEHA@GMAIL.COM','SHANTINAGAR','CHENNAI','TAMIL NADU',15)


-- 1.Create an Orders table which comprises of these columns  order_id, order_date, amount, customer_id

CREATE TABLE ORDERS
(
	ORDER_ID INT ,
	ORDER_DATE DATE,
	AMOUNT INT,
	CUSTOMER_ID INT
)

INSERT INTO ORDERS
VALUES(11, '1999-09-23', 23, 20),
	(12, '1998-08-22', 24, 30),
	(13, '1997-05-23', 2212, 70)


-- 2.Make an inner join on Customer & Order tables on the customer_id column 
SELECT *
FROM CUSTOMER INNER JOIN ORDERS ON CUSTOMER.CUSTOMER_ID=ORDERS.CUSTOMER_ID


-- 3.Make left and right joins on Customer & Order tables on the customer_id column
SELECT *
FROM CUSTOMER LEFT JOIN ORDERS ON CUSTOMER.CUSTOMER_ID=ORDERS.CUSTOMER_ID

SELECT *
FROM CUSTOMER RIGHT JOIN ORDERS ON CUSTOMER.CUSTOMER_ID=ORDERS.CUSTOMER_ID


-- 4.Update the Orders table, set the amount to be 100 where customer_id is 30
UPDATE ORDERS SET AMOUNT=100 WHERE CUSTOMER_ID=30